name: Quarkus Postgres CI

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: prime_calculator
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test Quarkus Application
          mvn package
          java -jar ./target/*-runner.jar
          curl -I -X GET "http://localhost:8080/health" -w "\n"
          curl -I -X GET "http://localhost:8080/hello" -w "\n"
