
name: Test Code and Publish package to the GitHub Packages

on:
  push:
    branches:
      - main
          
jobs:

  dependency-review:
    
    runs-on: ubuntu-latest
    steps:
    
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
        
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2

  publish-to-github:
    needs: dependency-review
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD:  ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    
    permissions:
      contents: read
      packages: write
      
    steps:
      - uses: actions/checkout@v3
          
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Test Quarkus Application
        run: mvn test

      - name: Publish to GitHub Packages
        run: mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
