name: Test Code and Publish package to the GitHub Packages

on:
  push:
    branches:
      - main
          
jobs:

  test-code:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD:  ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    
    steps:
    
      - name: Checkout and Setup Java 17
        uses: phro-sudo/GithubActionsTest/.github/actions/mysetup@main
        with:
          java-version: '17'
    
      - name: Test Quarkus Application
        run: mvn test


  publish-to-github:
    needs:
      - test-code
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD:  ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout and Setup Java 17
        uses: phro-sudo/GithubActionsTest/.github/actions/mysetup@main
        with:
          java-version: '17'

      - name: Publish to GitHub Packages
        run: mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
